### ISSUE TITLE
Consolidate tips and questions in piazza

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#110]
Continuation of #78

**Comment by vibhatha** [comment]
@badi @laszewsk 
Closed #78 
And start working on #110

**Comment by vibhatha** [comment]
Added more posts and I will keep this updated.

**Comment by vibhatha** [comment]
@badi @laszewsk 
Added more posts. Fixed things on piazza and file is already formatted with better indentation. And content is pushed and a pull request has been already sent.
