### ISSUE TITLE
What is the NEW_MIX folder on IU Box?

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#111]
@jemitchell It looks like you created this. What's the difference between the "NEW_MIX" and previous "Mix" folders?

**Comment by laszewsk** [comment]
if it was me, i do not remember

**Comment by badi** [comment]
It was @jemitchell based on the audit log for the directory

**Comment by jemitchell** [comment]
This directory was created to help @miaozhan  with discriminating against various videos.

**Comment by badi** [comment]
Can it be renamed to something more descriptive of its function?
"NEW_MIX" is rather open ended.

**Comment by jemitchell** [comment]
Yes, we could eliminate it. And reorganize the lectures in MIX

**Comment by badi** [comment]
@jemitchell please coordinate with @miaozhan to do so and close this issue when done.

**Comment by badi** [comment]
@jemitchell @miaozhan any progress?

**Comment by miaozhan** [comment]
I don't think that folder is needed.

**Comment by miaozhan** [comment]
folder removed.
