### ISSUE TITLE
Add missing mix files to IU Box

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#112]
Corollary for #90. Some lectures are out of date and not available on IU Box.
The current links point to outdated versions.
They need to be downloaded and added to Box, then updated as per #90

**Comment by laszewsk** [comment]
SO have all those been updated and cleaned?

ID	Description	Resources	Length
7	Big Data Application Structure	Slides	 
7.A	NIST Big Data Sub Groups	Slides	0:23:25
7.B	Big Data Patterns - Sources of Parallelism	Slides	0:23:51
7.C	First and Second Set of Features	Slides	0:18:26
7.D	Machine Learning Aspect of Second Feature Set and the Third Set	Slides	0:18:38
8	Aspects of Big Data Applications	Slides	 
8.A	Other sources of use cases and Classical Databases/SQL Solutions	Video	0:16:50
8.B	SQL Solutions - Machine Learning Example - and MapReduce	Video	0:18:49
8.C	Clouds vs HPC - Data Intensive vs. Simulation Problems	Video	0:20:26
11	Big Data Applications and Generalizing their Structure	Slides	 
11.A	NIST UseCases and Image Based Applications Examples I	Video	0:25:20
11.B	Image Based Applications II	Video	0:15:23
11.C	Internet of Things Based Applications	Video	0:25:25
11.D	Big Data Patterns - the Ogres and their Facets I	Video	0:22:44
11.E	Facets of the Big Data Ogres II	Video	0:15:09
12	More on Software Stack	Slides	 
11.A	More of Software Stack	Video	0:24:00

**Comment by badi** [comment]
No. Miao is still working on it. See #90

**Comment by miaozhan** [comment]
added and pull request submitted
