### ISSUE TITLE
Prepare tutorial on Github for Feb. 6

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#120]
I think this is duplicate of #71

**Comment by miaozhan** [comment]
Do we expect any Git talk next Monday (Feb. 6th) again? Or it is considered done after Jan 30th class?

**Comment by laszewsk** [comment]
just so people can finish homework, you can introduced general concpt of git and branching also.

so this would be more than just hw

**Comment by laszewsk** [comment]
please prepare to have talk ready

**Comment by badi** [comment]
@miaozhan @tonythomascn What is the status on this. Do you have a PR with these changes?

**Comment by miaozhan** [comment]
No new material added.

We followed our existing lessons and worked with students one-on-one to address their issues.

**Comment by dimitargnikolov** [comment]
Closing per @miaozhan's comment.
