### ISSUE TITLE
Verify all links in theory lectures go to youtube or correct box

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#121]
Possible duplicate of #75

**Comment by badi** [comment]
See also #139

**Comment by laszewsk** [comment]
I assign this to you to make a sanity check, please work with Jerome as he has fixed some slides and has a pull request putstanding that is however wrong as he did not rebase

**Comment by badi** [comment]
@dimitargnikolov @jemitchell Any progress?

**Comment by dimitargnikolov** [comment]
I looked at the links and they look fine. More detailed comment in a separate issue that I will link here when I find it.
