### ISSUE TITLE
Cluster Command

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#125]
- [x] Test dev branch from the source
- [x] Documentation and example on cluster command for Mark and other students 

- [x] Video by Vihbatha

**Comment by dimitargnikolov** [comment]
@tonythomascn, can we discuss in person tomorrow before group meeting? I don't know where we are on this.

**Comment by tonythomascn** [comment]
Vihbatha and I are already working on this. The cloud mesh video has shown the cm vm command. Also, Gregor agree not to make this too complicated by introducing too many commands.

What do you want know about?
