### ISSUE TITLE
Crash course on bash

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#132]
- [ ] rst page for this on web page
- [ ] video

**Comment by laszewsk** [comment]
what is update?

**Comment by laszewsk** [comment]
this was taken on by dimitar

**Comment by dimitargnikolov** [comment]
I made a video on this last week. It introduces a few useful commands while helping the students set up their environment on an Ubuntu VM: https://www.youtube.com/watch?v=LeTlm_ck2GI

It is also linked under the System lecture track.

The video points the students to these pages for reference information: 
https://cloudmesh.github.io/classes/lesson/linux/linux.html (Linux Shell)
https://cloudmesh.github.io/classes/lesson/linux/ssh.html (Using SSH Keys)

Is anything else required to close this?

**Comment by laszewsk** [comment]
so is this integrated in the lectures?

**Comment by dimitargnikolov** [comment]
Yes, there is a link to the video here: https://cloudmesh.github.io/classes/i524/lectures.html#lectures-systems

**Comment by dimitargnikolov** [comment]
I didn't make any modifications to the two lessons, but they seem sufficient. If you think anything in addition to the video and the two RST pages is necessary, let me know.

**Comment by laszewsk** [comment]
my question was different.

are thei in the csv lectures?

**Comment by dimitargnikolov** [comment]
Yes, I had updated lectures-systems.csv when I created the video.

**Comment by laszewsk** [comment]
i close as dimitar says he updated
