### ISSUE TITLE
Compile bibtex for latex.rst

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#133]
- [ ] LaTeX Users and Reference Guide, by Leslie Lamport ;
- [ ] LaTeX an Introduction, by Helmut Kopka;
- [ ] The LaTeX Companion, by Frank Mittelbach
- [ ] Reference manual
- [ ] not so short introduction

**Comment by laszewsk** [comment]
this seems duplicate to other task

**Comment by dimitargnikolov** [comment]
This is related to #145. I will create the intro/tutorial for #145 and include the references Badi included as checkboxes here.

**Comment by vibhatha** [comment]
I can work with @dimitargnikolov for this task. I will follow his lead and contribute.

**Comment by badi** [comment]
@laszewsk are you referring to #145 as well?

**Comment by vibhatha** [comment]
Compiling paper 1 was successfully done. The content is so far good. I will add some help links to help a student who is doing things from the scratch.

**Comment by dimitargnikolov** [comment]
@vibhatha, is there anything left to do on this?

**Comment by laszewsk** [comment]
close as no longer relevant
