### ISSUE TITLE
Create scripts to merge spreadsheets

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#135]
Can be done by hand.

Something like (after manually downloading csv files of the canvas and google rosters):

```bash
i524-compare --canvas canvas.csv --google google.csv
```

returns a in the form:

```
Name, HID, status
```

We also need an `--update-enrollment` to automatically mark the enrollment status in the google spreadsheet.

**Comment by laszewsk** [comment]
what is status

**Comment by dimitargnikolov** [comment]
This was done manually by Jerome and me in response to issue #216. Closing and will create an issue for next week, since we need to keep updating the spreadsheet.
