### ISSUE TITLE
Create LaTeX/BibTex FAQ for webpage

### ISSUE THREAD

**Issue by dimitargnikolov** [cloudmesh/classes#145]

**Comment by vibhatha** [comment]
I can discuss this with Dimitar and we can provide a good material.

**Comment by dimitargnikolov** [comment]
For this, I was thinking of building it around the paper template. That is, explain what is necessary for them to understand the template. I will work on a draft for this for Monday. @vibhatha, we can discuss before or after the Monday lecture.

**Comment by vibhatha** [comment]
@dimitargnikolov 
Can we talk before Tuesday meeting or after. I am full on Monday, I have 3 classes including the morning I524. Is it okay with you ?

**Comment by vibhatha** [comment]
Paper 1 compiles very well, for now everything is good and I will add some information regarding prior requirements and resources needed to get things done, if a student just refer this link without setting up initial stuff.

**Comment by laszewsk** [comment]
can you put link in here so we can review

**Comment by vibhatha** [comment]
Yes, I am adding the content and I will send the link ASAP.  (Within next few hours)

**Comment by vibhatha** [comment]
https://cloudmesh.github.io/classes/i524/paper1-hw.html#paper-1-homework
This works pretty well in Ubuntu 16.04 and I have compiled and made pdf.

**Comment by vibhatha** [comment]
Added the links to the FAQ.  And PR sent.

**Comment by dimitargnikolov** [comment]
This was done by Vibhatha. @vibhatha feel free to close if something looks complete, we can always reopen.
