### ISSUE TITLE
PRIORITY: i523 Final project reviews

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#153]
Jerome:

Students demand project review details.

a) Address each project and person that requests them
b) provide private google docs so you can share wikt me and badi
c) we will make sure reviews are ok
d) we will send private note to individual students with the review
e) will will discuss this over e-mail and not via github. github issue is only here to make sure you do not forget taks. I like all reviews for students that requested it to be ready by Feb 14. or earlier.

https://piazza.com/class/irqfvh1ctrg2vt?cid=1766
https://piazza.com/class/irqfvh1ctrg2vt?cid=1770
please look for other requests in piazza

**Comment by jemitchell** [comment]
What would be a good strategy for this item? Since most students are just requesting their project grade, should I just notify them and if they require specifies, we can regrade?
