### ISSUE TITLE
fix indentation for cascading in techlist

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#154]

**Comment by vibhatha** [comment]
@badi 
Do you mean in techlist-xx.rst, the indentation ?

**Comment by laszewsk** [comment]
just look at techlist*.rst
and faq
fix all indentation errors in all files

**Comment by vibhatha** [comment]
Yes I will do that.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
@badi 
How should I fix indentation ? I mean to have no conflicts, should just align one by one paragraph and commit each. I am using Emacs to do the task. Just suggest me, if there is a better way.

**Comment by laszewsk** [comment]
if you see indentation issue fix in behalf of student. I have done this yesterday for all that i saw were wrong. indentation can be seen in original raw file

ESC q in emacs does thsi nicely
first two lines must be on ndentation

**Comment by vibhatha** [comment]
Yes professor, I am doing the same way.
But the fact is when doing that task, should I commit each time when I
indent a single paragraph. I got conflicts due to this reason, a few times.

With Regards,
Vibhatha Abeykoon

**Comment by badi** [comment]
My approach would be.

1. Made sure your master is up to date
1. Create a new branch called issues/154
1. Commit and push each change.
1. Create a pull request after the first push. Set the title to WIP DO NOT MERGE fix:dev: fix indentation in techlist  (fixes #154)
1. Once done, edit the title to remove the WIP DO NOT MERGE

This way you can preview the merge while you work on it and verify that each commit passes the Travis test. Once merged you can delete you branch.

**Comment by vibhatha** [comment]
@badi 
I am not that much familiar with creating a new branch. Can I ask you this tomorrow, just for 5-10 minutes. So that I can execute this exactly as you say.

**Comment by badi** [comment]
Sure stop by anytime after 10

--

**Comment by vibhatha** [comment]
Great.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
Indentations fixed.
