### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#184]
One of the recent PRs has caused the build to break.
@cloudmesh/i524-sp17-ais @laszewsk Please do not merge until the travis job is finished. In only takes a couple minutes.

I'll dig through and fix this.

**Comment by laszewsk** [comment]
i thought i fixed it

**Comment by badi** [comment]
You talking about dae86c35a7cd81638553b29d92369a6eaa0b0024?
It looks like that does it.
