### ISSUE TITLE
Sample Paper 1

### ISSUE THREAD

**Issue by tonythomascn** [cloudmesh/classes#188]
Sample paper 1 on how to write paper 1 correctly.

**Comment by vibhatha** [comment]
Compiled the paper script and it's work well on Ubuntu 16.04. And I will update the document with Tony.

**Comment by tonythomascn** [comment]
Hi, Vibhatha.
Could you please add me as a collaborator for this repo?
Thank you.

Tony

**Comment by vibhatha** [comment]
Yes Tony, sorry for the delay.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
I already added you

https://github.com/vibhatha/sp17-i524/invitations

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
@tonythomascn 

Did you check the latest version of the paper ?

**Comment by tonythomascn** [comment]
I did. On Sunday night, I also did a minor change to it. However, since Gregor said we need to complete this paper as a real one. I think we need to extend it. Can you write why nagios is important and the next chapter, please? For the advantage or disadvantage chapter, I am not sure it’s ok or not. If you have a better angle to replace it, please do it. I will take a look at the rest and make them one piece.

**Comment by vibhatha** [comment]
Finalized the paper, now it is up to proof read and grammar check.

@tonythomascn @laszewsk

**Comment by laszewsk** [comment]
no longer relevant
