### ISSUE TITLE
Paper 2 postponed

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#189]
Paper 3 cancelled. Paper 2 due same time as Paper 3.

Update:
- Website
- Piazza
- Canvas

Post update on Piazza once everything is updated.

**Comment by dimitargnikolov** [comment]
I will send announcment once I've looked at the sample paper Tony and Vibhatha wrote. That way we can have a single announcement about paper 1 video, sample paper, and paper 3 cancellation. Will do tonight.

**Comment by dimitargnikolov** [comment]
Announcement sent. We can add the sample paper later, since I think it needs some edits.
