### ISSUE TITLE
travis fails on all because pdf does not work

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#196]
as we also craete the pdf document it seems that this fails on travis. Thus this will not be successful

**Comment by badi** [comment]
This is indication of a deeper problem.
I'll update the travis rules only build the website and not the i524-notes.pdf

**Comment by badi** [comment]
This is a bug in sphinx or sphinxcontrib-bibtex.

I've traced it to `app.env.bibtex_cache.get_label_from_key` [here](https://github.com/mcmtroffaes/sphinxcontrib-bibtex/blob/ae796eb7f4122451e2afab2d131a09fe9b2e6dd8/sphinxcontrib/bibtex/__init__.py#L58)

Example of tracing through:

- reference key in `refs.bib`: `www-cloud-google`
- cached key generated by sphinx: `wwwa`

It look like they truncate the bibtex key to three characters and then append more from the ascii table to enforce uniqueness.

**Comment by laszewsk** [comment]
error is now clearly visible in sphinx, for example in the jclouds entry

d to different cloud providers. The APIs also bring interoperability such that cloud platforms can communicate and exchange information using these common or shared interfaces. Jclouds or apache jclouds [www{] is a java based library to provide seamless access to cloud platforms. Jclouds library provides interfaces for most of cloud providers like docker, openstack, amazon web services, microsoft azure, google cloud engine etc

YOu see it uses { which is not possible in latex. Hence the reason why it works in sphinx, but fails in latex

**Comment by laszewsk** [comment]
I filed:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/110

please commet and improve bug report. If there is more than one person commenting on it experience shows they may fix it faster.

**Comment by badi** [comment]
I saw. I'm working on narrowing the error down.

**Comment by badi** [comment]
actually looks like it is in pybtex, not sphinxcontrib-bibtex

**Comment by badi** [comment]
if we can switch the pybtex label style to `number` it should resolve this issue.
