### ISSUE TITLE
attendence verification: HARD DEADLINE Feb 13

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#216]
- [x] dimitar gives attendence sheet to jerome
- [x] jerome adds attendence info to spreadsheet
- [ ] deadline Feb 13

- [ ] get Gregor a list of people who haven't submitted a pull request
- [ ] Gregor needs to upload this to the university

This is a reminder that Attendance verification is due on February 13th this term

We need to have it before Wed 10am whne we have the meeting with the CANVAS expert. e.g. we need to have column attendence where we note last time student communicated to us in any form (if available).

Dimitar has also attendence sheet from class, so that should be easy

**Comment by dimitargnikolov** [comment]
I will just enter the attendance into the spreadsheet today, since I need to be in Info East and don't know if I can come to Smith.

**Comment by dimitargnikolov** [comment]
I've updated the attendance in the spreadsheet, contacted the problematic students and cc-ed Gregor.

**Comment by jemitchell** [comment]
The google spreadsheet has been updated with github and piazza usernames.


Thanks,
Jerome

**Comment by badi** [comment]
@jemitchell could you check off the items that are done.

**Comment by jemitchell** [comment]
I have updated!

**Comment by dimitargnikolov** [comment]
This was completed last week.
