### ISSUE TITLE
Biovia Pipeline Pilot

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#596]
A student pointed that out the following, not sure where to integrate this?

+Application List and Description
 +================
 +
 +1. Biovia Pipeline Pilot is a workflow application that allowes the creation of custom reports, 
 +can act as the 'middleman' between multiple databases, can be used to create user interfaces, perform 
 +analytics with direct connection to R and SAS tools, and a ton of other user developed solutions. 
 +
 +
 +.. ................................................................  links
 +
 +Vendor Sites
 +============================
 +
 +- `Biovia Pipeline Pilot`_: ``http://accelrys.com/products/collaborative-science/biovia-pipeline-pilot/``
 +

**Comment by ssheybani** [comment]
Is this issue supposed to be closed (as Gregor mentioned in #570)?

**Comment by ssheybani** [comment]
Apparently the student has already created a file for it in the main directory. We can just move the file into a new directory named "technologies" similar to what we had in i524. Should I do that?

**Comment by laszewsk** [comment]
you are responsible. I do not even know where to place it I do not think that any directory we have fits this. This is almost like a technology for i524, but I am not sure. So if you can give a suggestion what to do with it that would be great.

**Comment by ssheybani** [comment]
I suggest that we create a new directory named "student contributions" in "cloudmesh/classes/tree/master/docs/source/i523/2017" and put this file over there, and name it "technologies".

**Comment by laszewsk** [comment]
remember we cant have spaces

can you provide exact path

**Comment by ssheybani** [comment]
Alright. The path would be https://github.com/cloudmesh/classes/tree/master/docs/source/i523/2017/student-contribution
And the file would be technologies.rst
Should I go ahead and create that?

**Comment by laszewsk** [comment]
lets do 

> https://github.com/cloudmesh/classes/tree/master/docs/source/i523/2017/contribution <https://github.com/cloudmesh/classes/tree/master/docs/source/i523/2017/contribution>/student
>

**Comment by jzerick** [comment]
There are open source, general purpose alternatives to this tool.

**Comment by laszewsk** [comment]
can you identify them and add to the section. Saber has written somewhere a rst section or page about this. I think its only free for students ... but I am not sure.

**Comment by laszewsk** [comment]
overdue

**Comment by ssheybani** [comment]
I have copied the student's explanation in here:
https://github.com/cloudmesh/classes/blob/master/docs/source/i523/2017/student-contribution/technologies.rst

**Comment by ssheybani** [comment]
I am closing this issue as I have already incorporated the note in the class Github.
@jzerick can reopen it and add the descriptions for alternative tools if she wants. But I assume we might have tasks of higher priority now.
