### ISSUE TITLE
PDF version of slides

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#607]
Publish all ppt also as PDF and integrate in slides after all videos have been published or you have nothing to do. PLease work with Grace. She will ccordinate and assign you setions you will do. If you had sections before. I suggest you creat the pdf upload them to google and add them to your section

**Comment by laszewsk** [comment]
overdue

**Comment by ssheybani** [comment]
* [x] 3.1
* [x] 3.2
* [x] 3.3
* [x] 3.4
* [x] 3.5
* [x] 3.6
* [x] 3.7
* [x] 3.8
* [x] 3.9
* [x] 3.10
