### ISSUE TITLE
add ta as admin to projects

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/classes#612]
all 100 already don, work on 200 300
https://github.com/bigdata-i523/hid201/settings/collaboration

Add the ta as admin to eack project

use web browser and change number, its probably the fastest do not bother doing script

**Comment by ssheybani** [comment]
I added people for hid330 and hid327. All the other sub-directories were already managed as far as I understood.

**Comment by ssheybani** [comment]
I noticed that some numbers don't have any hid assigned to them. so I looked at the hid table and deduced that they are probably for the students that have dropped the course. Except for 341, 342. So all the others are covered now.

**Comment by miaojiang1987** [comment]
I think this task is pretty done.
