### ISSUE TITLE
Provide instructions for installing Ubuntu 16.04 on Virtualbox on Windows 10

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#66]

**Comment by vibhatha** [comment]
I will do this. I will update the course website by tonight, including all the instructions with clear documentation.

**Comment by badi** [comment]
Also needs screenshots and/or video

**Comment by vibhatha** [comment]
I have already created a video and it is on our channel. I am waiting for instructions on approval of video or to replace it with the videos made by Prof. Gregor, because I find them much better than mine, and they are already in the Youtube channel.
