### ISSUE TITLE
Separate virtualbox and ubuntu on virtualbox installation

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#70]
There's a `docs/source/lesson/linux/ubuntu.rst` that documents how to install ubuntu on virtualbox.
The virtualbox-specific instructions should be separated into their own `virtualbox.rst`

**Comment by vibhatha** [comment]
I have split the documentation to two files.

**Comment by badi** [comment]
Does PR #88 resolve this?
If so, please close this issue.
