### ISSUE TITLE
Github lesson for monday

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#73]

**Comment by badi** [comment]
@miaozhan did PR #86 also fix this?

**Comment by miaozhan** [comment]
@badi My interpretation of this issue was: prepare Monday's lecture. Like using our git chapters as the outline and give a talk based on them.
This means after Monday's 9:30am, it is done anyway...
But please comment so I can have a clearer understanding.

**Comment by badi** [comment]
That was my understanding as well.

I would ask that when you are done preparing the lecture that you indicate so on this issue and then close it. It will make it easier for @laszewsk and I to see the overall status of this milestone progress a la https://github.com/cloudmesh/classes/milestone/1

**Comment by miaozhan** [comment]
close it and pretend I know how to lecture.
