### ISSUE TITLE
Python lesson for Monday

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#74]

**Comment by laszewsk** [comment]
added dict
added python as draft to released slides
added some links to python tutorial

**Comment by badi** [comment]
@dimitargnikolov Related to PR #98 add a warning to the python intro about alternative python installations.

**Comment by badi** [comment]
What is the status of this issue? Can this be closed?

**Comment by dimitargnikolov** [comment]
Waiting on my pull request to be approved for this. I will probably do a few more edits today and will close before our meeting tomorrow.

**Comment by badi** [comment]
Is that #109? I just did a review and suggested some edits.

**Comment by dimitargnikolov** [comment]
Yes, that's the pull request. Thanks for the feedback. I will implement the suggestions today and update here when done.

**Comment by badi** [comment]
@dimitargnikolov I closed this during the merge of #113. Please reopen if there is still more to be done

**Comment by dimitargnikolov** [comment]
Reopening since I want to add an example of using map and another using the multiprocessing API. Will add tonight.

**Comment by dimitargnikolov** [comment]
Did some cleanup and minor edits, so it's ready to publish. 

I will include the map/reduce example in the big data tutorial for next week per our meeting today.
