### ISSUE TITLE
Verify links work for released lectures

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#75]
check if all lectures and links to them as well as the slides on the “released” lectures are indeed working

**Comment by badi** [comment]
What is the status of this issue?

**Comment by badi** [comment]
@jemitchell  What is the status of this issue?

**Comment by jemitchell** [comment]
This is complete. The links for released and unreleased have been updated.

**Comment by badi** [comment]
Which PR contains your changes?
[I don't see any](https://github.com/cloudmesh/classes/pulls?utf8=%E2%9C%93&q=is%3Apr%20author%3Ajemitchell%20) which could contain these fixes.
