### ISSUE TITLE
Prepare linux lesson for monday

### ISSUE THREAD

**Issue by badi** [cloudmesh/classes#77]
@laszewsk @jemitchell @dimitargnikolov @tonythomascn @vibhatha @miaozhan Who is doing this?

**Comment by laszewsk** [comment]
added linux to lectures
who is doing this on monday

**Comment by dimitargnikolov** [comment]
It doesn't look like this was assigned at our last meeting, but I will take care of it together with the Python tutorial.

**Comment by badi** [comment]
What is the status of this issue? Can this be closed?

**Comment by dimitargnikolov** [comment]
I need to record a video on this. I will do this today and close the issue.

**Comment by badi** [comment]
Can this be closed now?

**Comment by dimitargnikolov** [comment]
I will close it a little later tonight. I had to rerecord the videos with better sound. I am finishing the last video after which I'll put them all together and upload to YouTube.

**Comment by dimitargnikolov** [comment]
Video is done and available at https://www.youtube.com/watch?v=LeTlm_ck2GI.

I've updated the Systems Track page with the link.
